---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-greetings-app
spec:
  selector:
    matchLabels:
      app: go-greetings-app
  template:
    metadata:
      labels:
        app: go-greetings-app
    spec:
      containers:
        - name: go-greetings-app
          image: ghcr.io/simonstiil/go-greetings-app:main
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: go-greetings-app
spec:
  selector:
    app: go-greetings-app

  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-greetings-app
  labels:
    app: go-greetings-app
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
spec:
  ingressClassName: traefik
  rules:
  - host: go-greetings-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-greetings-app
            port:
              number: 8080